### ISSUE TITLE
[Bug] jest svg 에러

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#66]
## 📃 Description

jest가 svg파일을 검사하고 오류를 발생시킴

## ☑ Todo

- [x] 바보1 해결
- [x] 바보2 해결

## 에러 내용
```
 ✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 2 files
    ❯ frontend/**/*.{ts,tsx} — 2 files
      ✖ npm run test:frontend:lint-staged [FAILED]
    ✔ **/* — 2 files
    ❯ *.{ts,tsx} — 2 files
      ✔ eslint --fix
      ✖ prettier --write [KILLED]
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ npm run test:frontend:lint-staged:
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Function.findNodeModule (/Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/jest-resolve/build/resolver.js:170:43)
    at resolve (/Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/jest-config/build/utils.js:107:41)
    at /Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/jest-config/build/normalize.js:735:34
    at Array.map (<anonymous>)
    at /Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/jest-config/build/normalize.js:731:34
    at Array.reduce (<anonymous>)
    at normalize (/Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/jest-config/build/normalize.js:608:14)
    at async readConfig (/Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/jest-config/build/index.js:160:45)
    at async readConfigs (/Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/jest-config/build/index.js:424:26)
    at async runCLI (/Users/sangkkim/Workspace/transcendence/frontend/react-app/node_modules/@jest/core/build/cli/index.js:151:59)

> transcendence@1.0.0 test:frontend:lint-staged
> cd frontend/react-app && npm run test:lint-staged /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sidaBarList/index.styled.ts /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sideBar/chattingSideBar/index.tsx


> react-app@0.0.0 test:lint-staged
> jest --passWithNoTests --findRelatedTests /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sidaBarList/index.styled.ts /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sideBar/chattingSideBar/index.tsx


✖ prettier --write:
[warn] Ignored unknown option { "prettier/prettier": ["error", { singleQuote: true, parser: "flow" }] }.
husky - pre-commit hook exited with code 1 (error)

 ~/Workspace/transcendence/frontend/react-app  feat/#46/channel-list-page +2 !5 ··········· 03:51:03 PM 
❯ git commit -m "Feat: chatting sidebar에 channel, dm 리스트 추가 #46"
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 2 files
    ❯ frontend/**/*.{ts,tsx} — 2 files
      ✖ npm run test:frontend:lint-staged [FAILED]
    ✔ **/* — 2 files
    ✔ *.{ts,tsx} — 2 files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ npm run test:frontend:lint-staged:
 FAIL  src/__tests__/components/profileSideBar.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/assets/icons/CaretDown.svg:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                                                      ^

    SyntaxError: Unexpected token '<'

      1 | import { styled } from "styled-components";
    > 2 | import Arrow from "@assets/icons/CaretDown.svg";
        | ^
      3 |
      4 | export const Container = styled.div`
      5 |   display: flex;

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (src/components/common/sidaBarList/index.styled.ts:2:1)
      at Object.<anonymous> (src/components/common/sidaBarList/index.tsx:2:1)
      at Object.<anonymous> (src/components/common/sideBar/chattingSideBar/index.tsx:6:1)
      at Object.<anonymous> (src/components/common/sideBar/index.tsx:2:1)
      at Object.<anonymous> (src/__tests__/components/profileSideBar.test.tsx:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.302 s
Ran all test suites related to files matching /\/Users\/sangkkim\/Workspace\/transcendence\/frontend\/react-app\/src\/components\/common\/sidaBarList\/index.styled.ts|\/Users\/sangkkim\/Workspace\/transcendence\/frontend\/react-app\/src\/components\/common\/sideBar\/chattingSideBar\/index.tsx/i.

> transcendence@1.0.0 test:frontend:lint-staged
> cd frontend/react-app && npm run test:lint-staged /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sidaBarList/index.styled.ts /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sideBar/chattingSideBar/index.tsx


> react-app@0.0.0 test:lint-staged
> jest --passWithNoTests --findRelatedTests /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sidaBarList/index.styled.ts /Users/sangkkim/Workspace/transcendence/frontend/react-app/src/components/common/sideBar/chattingSideBar/index.tsx

husky - pre-commit hook exited with code 1 (error)
```

**Comment by chanwoong1** [comment]
이거 해결했는데 디벨롭에 없을거예요 오늘안에 커밋해서 올릴게요

**Comment by sang-kyeong** [comment]
넵넵!
